deploy:
  provider: heroku
  api_key:
    secure: ZDurkFYDO9sQ+wHrDGwLaQ8t1DsRuZS3jCYXlL0HGxTFeN6E1xuaNWdhRYBQxWzP7rDCEtC98/74yA4AVGqqsF4q8mMxfbh1KLQDnbBsUxDHxp2+6ER3RdixnWut6XXE0hKPwCrM9mlJlPzlpyuNGusN0N840tdiZagp0t4tPHmgCyA/ZVP4ADwrJV55HxzPH40IUos6TbFqgptSIgkY3tt35ZUBXSfPHJuZHxI8erWDwIx4WwoUdmMS3ZytdSi8NeXunXRgLeM/OdG47rvOANO6Eef11cnAf/xx+Ugdo10o6CYq2s4lJ1Ekv81DeYOj3TQYTSfVxkSQACVF4LQZtoQh++hbMTezUcwgDJXCQy0pLk5qh+Doj33craja2+NmKQbpBEZwE87xtdn5rASrnm5XmCQxZutvUhJA+BPr2tTQUF4ZID8qjBNCmy5m3thHzwOLyAYv6LJTz1ANpo8ht3QWlpvqBBLm+DL2A8zJ3i6FI9swsdPXc2KiZ0IvaaKmw7XQSY+0m1rAyymJr3nxk0OSPJt5riYr6gG4V/ZWmui6G/tIy5kKumMzRqj4NcCPm/4B/Ykzn14SY8j4igPRj2fr5wOa98bw9T5hUxQsc3phbqmFAxG49pBS8k2J5Ph0j54KMOHoLFjNT+zH4Uxzrs5J9EUXOM3S+PYpzuQab2A=
  app: project-103-miracle-workers
  on:
    repo: UVA-CS3240-S19/project-103-miracle-workers
