language: python
python:
- 3.6.7
sudo: true
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  # - PGPORT=5433
  - DJANGO_SETTINGS_MODULE="housing_project.settings"
  - PYTHONPATH="/home/travis/build/sgmedlin/project-103-miracle-workers"
  - PIP_USE_MIRRORS=true
  # - BUILD_ON_TRAVIS=true
  matrix:
  - DJANGO=2.1.7 DB=postgres
install:
- pip install -q -r requirements.txt
- pip install -q Django==$DJANGO --quiet
- pip install -q psycopg2
# before_script:
# - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
# - sudo service postgresql restart
# - sleep 1
# - psql -c 'create database travis_ci_db;' -U postgres
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: JcRF3HJXmfuWZ4PnzfcjJni9uSpkhOIhtUTUTBl3yXhXL7Audidr3qZOOzJb7Ngz+66lr7PLevZPhC6u7469rFV49KCeYplqZ+SnwrZtf1Y2TC2vv6ehwDdQduEEueER+dx20sQUnHPpxlDc8ShnHSjBnPkeTnw4XfOWPSWKm4qPUU2xtvDtCFoY2JKCXn58z1WIieqCYVHo5YVUEaC6S70s1rQPfdD9YsDDSTr0sM9irttNZw4Y40DWC1Dcco/LPijeomIhobjokDDNL3xhXh3Sa8iyYQbyD1P7tYbqBYUQw1aomxG18XXlmgxCbsZ7ZQgLKNbgvyX6S+UBxcs9Xmx6ztDKxRqB4wb2EggQw4LEkUXWZgqDLjqTIt8P8K2mnsKkeT7vFRJ7ZWmyBKd8vurWoLnu07DJ7ebpgRplwJ/zzypT+ZQWZoGSrZcno2hbkRsjOp0gMHx3K3VIyOjnL2lQxjqFxEyl6/7+YdIbe31I5VEdJm79fhsjlSAfJxgjOgfSZVGr7jnBFw+lt4nAMj+qOTBnRQmCWZvmTA0LxioBjLddDswmDVuXVOxxiIkw4vsPMEFQIcQzejkSMWeaLNf6DMyyySOlYh29WS7G1OWymxMPg6HqktEDEqtIeJau3Nf482vdO8K8xpTE6RDE3s8WdxgWGm0T2o7srgzjQdw=
  app: miracle-workers-housing-app