language: python
python:
- "3.6.7"

# services: postgresql
sudo: true

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - PGPORT=5433
    - DJANGO_SETTINGS_MODULE="housing_project.settings"
    - PYTHONPATH="/home/travis/build/sgmedlin/project-103-miracle-workers"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
    
  matrix:
    - DJANGO=2.1.7 DB=postgres
  # secure: "vXd06OqF+f6vybaiGljYpTqnD0Xl6Yjs4mlO7SwcAOVKzPtJ9A3nx5jBF2RZyNq+E0Nk4e1Wioh5cl2x3jv1UQ2sCmyDEqY6n4s54sc0J2CQGnEI1hnuE9V90kCzptRzI+hmNHljUFxwMraQqZZFho5i/mOtLu3u6XrTajhyP4fLiwwLGUGBWUwI7Xia6AHVgEAba1Y5h7HVw49hnejL/vEu4uLY7c+2XKQfz170mwNi9Gs5MdZ54+olKVWUWRD/AuLixISIrljfsWva1gmwpcAFy4rGz639CJ2FheUV7Ruc7yLybJ+AEKdH6t5HUStjhHvLht+8UjomdpdlX5VyjcasKXLeOkgpIw0ToyAZtAx54mV+H2a0BYWcjzYevlwFFqJe3+7OZvyJpfqRTEpCXmYXV0I0pL6CAVF5dqMhaiO0AFOLjjyJoyYl4xeZwmczS8/plW2SxF9t4nvVR1YlqwFtdyRkj88e/swoT3faXT+7Jqh8D0HDdXdOql7oBtgPP3wgMksvK02Ewfr32aZZFNGHzJHKCbarp+GqWci8zU08QAysk4u9hlqqOhm828b4zcyttt6OkC3bEMkCtnz3XYAOyhp1MDkG63yRvO+OJg6YPuO8GNfY9SJc4hiMqoTQCPFNh7ir0iV7p1OhJdojopsU+DEOqYTIXwS/1VFgweY="


#commands to install dependencies
install:
  - pip install -q -r requirements.txt
  - pip install -q Django==$DJANGO --quiet
  - pip install -q psycopg2

before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  # - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  # - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"
  - psql -c 'create database travis_ci_db;' -U postgres

#command to run the test suite
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test